name: Tweet Capiron Every 4 Hours

on:
  workflow_dispatch:  # Allows manual trigger via GitHub Actions
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours at 00 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository content
        uses: actions/checkout@v3  # Ensure you're using the latest version of the checkout action

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a stable Python version for better compatibility

      # Step 3: Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure requirements.txt is in the repo

      # Step 4: Execute Python script
      - name: Execute Python script (main.py)
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py
